markdown: redcarpet
highlighter: rouge
permalink: /:categories/:title.html
url: 
lsi: false

paginate: 8 
paginate_path: "page:num"

title: Soakit 's Blog
description: Soakit's Blog, powered by Jekyll...
author: Erko liu

plugins: [jekyll-paginate]

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
